import { colors } from "./tagColors";

export const PROPOSAL_CLASS_TOKENOMICS = "Tokenomics";
export const PROPOSAL_CLASS_GRANTS = "Grants";
export const PROPOSAL_CLASS_ELECTION = "Election";
export const PROPOSAL_CLASS_PROTOCOL_UPGRADE = "Protocol Upgrade";
export const PROPOSAL_CLASS_SERVICE_PROVIDER_SELECTION =
    "Service Provider Selection";
export const PROPOSAL_CLASS_CHAIN_DEPLYMENT = "Chain Deployment";
export const PROPOSAL_CLASS_GOVERNANCE = "Governance";
export const PROPOSAL_CLASS_OTHER = "Other";

export const PROPOSAL_CLASSES = [
    PROPOSAL_CLASS_TOKENOMICS,
    PROPOSAL_CLASS_GRANTS,
    PROPOSAL_CLASS_ELECTION,
    PROPOSAL_CLASS_PROTOCOL_UPGRADE,
    PROPOSAL_CLASS_SERVICE_PROVIDER_SELECTION,
    PROPOSAL_CLASS_CHAIN_DEPLYMENT,
    PROPOSAL_CLASS_GOVERNANCE,
    PROPOSAL_CLASS_OTHER,
];

export const PROPOSAL_COLORS = {
    [PROPOSAL_CLASS_TOKENOMICS]: colors[0],
    [PROPOSAL_CLASS_GRANTS]: colors[1],
    [PROPOSAL_CLASS_ELECTION]: colors[2],
    [PROPOSAL_CLASS_PROTOCOL_UPGRADE]: colors[3],
    [PROPOSAL_CLASS_SERVICE_PROVIDER_SELECTION]: colors[4],
    [PROPOSAL_CLASS_CHAIN_DEPLYMENT]: colors[5],
    [PROPOSAL_CLASS_GOVERNANCE]: colors[6],
    [PROPOSAL_CLASS_OTHER]: colors[7],
};
