import DummyLogo from "@/public/assets/logov1.png";

export const dummyData = [
    {
        id: 1,
        name: "Protocol 1",
        icon: DummyLogo,
        primaryColor: "red",
        backgroundColor: "rgba(255, 0, 0, 0.1)",
        forumURL: "https://www.google.com",
        forumIcon: DummyLogo,
        forumTitle: "Optimistic digest",
        forumWeeklySummary:
            "This week's main topics include RetroPGF, social graphs, and smart contracts.",
        forumNumReplies: 65,
        forumNumNewPosts: 5,
        forumNumTrendingTopics: 7,
        forumTrendingPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 70,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
        forumLatestPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
    },
    {
        id: 2,
        name: "Protocol 2",
        endTime: new Date(),
        icon: DummyLogo,
        primaryColor: "blue",
        backgroundColor: "rgba(0, 0, 255, 0.1)",
        forumURL: "https://www.google.com",
        forumIcon: DummyLogo,
        forumTitle: "Optimistic digest",
        forumWeeklySummary:
            "This week's main topics include RetroPGF, social graphs, and smart contracts.",
        forumNumReplies: 65,
        forumNumNewPosts: 5,
        forumNumTrendingTopics: 7,
        forumTrendingPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
        forumLatestPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
    },
    {
        id: 3,
        name: "Protocol 3",
        endTime: new Date(),
        icon: DummyLogo,
        primaryColor: "green",
        backgroundColor: "rgba(0, 255, 0, 0.1)",
        forumURL: "https://www.google.com",
        forumIcon: DummyLogo,
        forumTitle: "Optimistic digest",
        forumWeeklySummary:
            "This week's main topics include RetroPGF, social graphs, and smart contracts.",
        forumNumReplies: 65,
        forumNumNewPosts: 5,
        forumNumTrendingTopics: 7,
        forumTrendingPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
        forumLatestPosts: [
            {
                id: 1,
                title: "Bootcamp Women in Web3 by Women Biz",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1467,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "April 4, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 2,
                title: "Season 5: Intents Budget Proposal #2",
                tags: ["Token House"],
                postURL: "https://www.google.com",
                numViews: 3908,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "March 21, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 3,
                title: "[READY TO VOTE] AI Assistance for governance support Mission Request",
                tags: ["Mission Requests", "season-5", "Intent-4"],
                postURL: "https://www.google.com",
                numViews: 1290,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 4,
                title: "Upcoming retro rounds and their design",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 7689,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "January 12, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
            {
                id: 5,
                title: "Lorem ipsum",
                tags: ["Retro PGF"],
                postURL: "https://www.google.com",
                numViews: 1000,
                numQuotes: 64,
                numComments: 12,
                summary:
                    "The Grants Council proposes reallocating 1.040.000 OP from the Gov Fund to support various missions aimed at enhancing the Optimism ecosystem, including making Optimism the primary home for liquid-staked eth and developing open-source tooling. The community, including key delegates, has reacted positively, supporting the proposal's advancement to a vote.",
                insights:
                    "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor",
                date: "February 3, 2024",
                consensusSentimentPercent: 63,
                consensusSentimentMajority: "yes",
                communityFeedback: [
                    'Strong support exists for the "Decentralized rollup-as-a-service" project, with emphasis on the team\'s experience and clearn miltestone.',
                    "Skepticism was expressed about the feasibility of a truly decentralized RaaS and the team's experience with necessary technology.",
                ],
                popularVoice: {
                    author: "Sam.sol",
                    text: "I am an Optimism delegate with sufficient voting power and I believe this proposal is ready to move to a vote.",
                    numQuotes: 89,
                },
                timeline: {
                    start: "2/1",
                    end: "2/5",
                    primaryColor: "#FFA3AE",
                    secondaryColor: "rgb(255, 0, 0)",
                    percentProgress: 60,
                },
            },
        ],
    },
];
